/**
 * The security headers, declared once.
 *
 * They have to reach two kinds of response, and the two mechanisms do not share a
 * list: Cloudflare's `_headers` file covers everything served from the assets
 * binding, while responses the Worker generates itself have to be labelled in the
 * Worker. That is a platform split, not two opinions about what the headers are.
 *
 * The list lives here, `src/middleware.ts` sends it on every response it
 * generates, and `npm run headers` renders it into `public/_headers` at build
 * time. One declaration, two consumers.
 *
 * HSTS stays out of this list on purpose. The dashboard sets it zone-wide
 * (SSL/TLS → Edge Certificates → HSTS), which is what lets one header cover the
 * `www` redirect as well, because that redirect is a zone setting that never
 * reaches the Worker. Declaring HSTS here too would send it twice.
 */

/** Sent on every response the Worker generates. */
export const SECURITY_HEADERS = {
	"X-Content-Type-Options": "nosniff",
	"Referrer-Policy": "strict-origin-when-cross-origin",
	"Permissions-Policy":
		"accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), xr-spatial-tracking=()",
	"Content-Security-Policy":
		"frame-ancestors 'none'; base-uri 'self'; object-src 'none'; form-action 'self'",
} as const;

/**
 * The `/catalogue.json` cache rule.
 *
 * The static asset is the only copy of the corpus, so the window is short: five
 * minutes fresh, long enough that the overwhelming majority of requests are served
 * from cache. It only changes with a deploy, which a push causes, so an hour of
 * staleness on top means a corpus edit lands within the hour rather than the day.
 */
const CATALOGUE_CACHE_CONTROL = "public, max-age=300, stale-while-revalidate=3600";

/** The body of `public/_headers`, with the reasoning above in it. */
export function securityHeadersFile(): string {
	const rules = [
		"# Security headers for prerendered pages and static assets.",
		"#",
		"# Generated by `npm run headers` from src/lib/security-headers.ts. Do not edit:",
		"# that file is the declaration, and this is what the build writes from it.",
		"#",
		"# Cloudflare Workers Static Assets applies this file to responses served from the",
		"# ASSETS binding. Worker-generated responses do not go through it:",
		"# src/middleware.ts sends the same headers from the same module.",
		"#",
		"# HSTS is deliberately absent: it is set zone-wide in the Cloudflare dashboard",
		"# (SSL/TLS -> Edge Certificates -> HSTS) so that it also covers the www redirect,",
		"# which never reaches the Worker. Setting it here too would emit it twice.",
		"#",
		"# The Astro Cloudflare adapter prepends its immutable Cache-Control rule for",
		"# /_astro/* to this file at build time.",
		"",
		"/catalogue.json",
		`  Cache-Control: ${CATALOGUE_CACHE_CONTROL}`,
		"",
		"/*",
		...Object.entries(SECURITY_HEADERS).map(([name, value]) => `  ${name}: ${value}`),
		"",
	].join("\n");
	return rules;
}
